# 一、ndarray
## 1.ndarry特性
多维性

In [2]:
import numpy as np

创建一个零维数组

In [2]:
arr = np.array(5) # 创建0维ndarry数组
print(arr)
print('arr的维度：', arr.ndim) # arr.ndim = number of dimensions arr
print(arr.dtype)

5
arr的维度： 0
int64


创建一个一维数组

In [3]:
arr = np.array([1,2,3]) # 创建1维ndarry数组
print(arr)
print('arr的维度：', arr.ndim) # arr.ndim = arr.number of dimensions 

[1 2 3]
arr的维度： 1


创建一个二维数组

In [4]:
arr = np.array([[1,2,3],[4,5,6]]) # 创建2维ndarry数组
print(arr)
print('arr的维度：', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度： 2


# 同质性

In [5]:
arr = np.array([1, 'error']) # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

['1' 'error']


In [6]:
arr = np.array([1, 2.5]) # 整数浮点数同时被强制转换成相同的数据类型
print(arr) # 整数 1 转换为 1.

[1.  2.5]


# ndarry的属性

In [ ]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)

1
数组的形状： ()
数组的维度 0
元素的个数： 1
元素的数据类型： int64


In [18]:
arr = np.array([1,2,3])
print(arr)
print('数组的形状：', arr.shape) # (3,) 以元组形式表示一维数组
print('数组的维度', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)

[1 2 3]
数组的形状： (3,)
数组的维度 1
元素的个数： 3
元素的数据类型： int64


In [23]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置：', arr.T, sep='\n')

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度 2
元素的个数： 6
元素的数据类型： int64
元素的转置：
[[1 4]
 [2 5]
 [3 6]]


# 3.ndarray的创建

In [27]:
# 基础的创建方法
list1 = [4,5,6]
arr = np.array(list1,dtype=np.float64)
print(arr.ndim)
print(arr)

1
[4. 5. 6.]


In [28]:
arr1 = np.copy(arr)
print(arr1)

[4. 5. 6.]


In [30]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [31]:
# 全1
arr = np.ones((3,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# 未初始化
arr = np.empty((3,3)) # 快速分配指定形状的内存空间，但不会主动初始化元素值
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.empty((4,3)) # 
print(arr)

[[1.03918611e-311 2.81617418e-322 0.00000000e+000]
 [0.00000000e+000 2.28139657e+256 2.42336543e-057]
 [7.48136191e-091 2.70237005e-056 1.53430236e-052]
 [6.15769229e+170 6.48224659e+170 4.93432906e+257]]


In [40]:
arr = np.full((4,3), 2025)
print(arr)

[[2025 2025 2025]
 [2025 2025 2025]
 [2025 2025 2025]
 [2025 2025 2025]]


In [44]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr, 2026)
print(arr1)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]]


In [47]:
# 等差数列 2 4 6 8 10
arr = np.arange(1,10,1) # start, end, step(步长)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [49]:
# 等间隔数列
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr = np.linspace(0,100,5,dtype=int)
print(arr)
arr = np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [57]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2) # 将零-四分为0,2,4三个数 再以2^0,2^2,2^4取值
print(arr)
arr = np.logspace(0,4,3,base=3)
print(arr)

[ 1.  4. 16.]
[ 1.  9. 81.]


# 特殊矩阵

In [60]:
# 单位方阵
arr = np.eye(3)
print(arr)

# 单位矩阵
arr = np.eye(3,4,dtype=int)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [61]:
# 对角矩阵
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [68]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.84978881 0.83910621 0.37607636]
 [0.37039397 0.80944183 0.82702433]]


In [ ]:
# 生成指定范围区间的浮点数
arr = np.random.uniform(60,100,(3,3))
print(arr)

[[91.71275906 65.08062747 72.24733471]
 [95.70674022 68.48560407 95.89255297]
 [74.58361814 63.31519358 65.2904918 ]]


In [70]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3,30,(3,3))
print(arr)

[[17  3 15]
 [23 10  4]
 [19 15  5]]


In [ ]:
# 生成随机数列（正态分布）
arr = np.random.randn(3,3)
print(arr)

[[ 0.12472413 -0.38695975  0.49559456]
 [-0.69812569 -0.15457723  1.17704226]
 [ 0.39200015  0.69630327 -0.16670503]]


In [74]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


4.ndarray的数据类型  
布尔 bool  
整数 int  
浮点 float  
复数 complex  

In [ ]:
arr = np.array([0.0,2.0],dtype='bool')
print(arr)

arr = np.array([1.0,2.0],dtype=np.int8) 
print(arr)

[False  True]
[1 2]


5.索引与切片

In [ ]:
# 一维 数组的索引与切片
arr = np.random.randint(1, 100, 20)

[11  7 76 19  4 78 18 44 17 19 80 91 60 72 76 30 46  7 64 79]


In [84]:
print(arr)

[11  7 76 19  4 78 18 44 17 19 80 91 60 72 76 30 46  7 64 79]


In [ ]:
print(arr[0])
print(arr[:3])
print(arr[(arr>10)&(arr<70)]) # 通过arr>10并且arr<70生成布尔掩码数组，通过arr[mask]用掩码筛选元素
# 布尔掩码数组 [False  True False  True False  True]
# Numpy只保留mask为True位置的元素

11
[11  7 76]
[11 19 18 44 17 19 60 30 46 64]


In [88]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[25 19 94 34 79 43 95  4]
 [19 71 53 23 15  5 28 76]
 [ 9  7 27 80 83 79 11 34]
 [86 18 41 83 43 61 85 31]]


In [ ]:
print(arr[0,3]) # 获得34
print(arr[:2,:])
print() # 空行
print(arr[arr>50]) # 返回一维数组
print(arr[2]) # 获取第三行
print(arr[:,3])

34
[[25 19 94 34 79 43 95  4]
 [19 71 53 23 15  5 28 76]]

[94 79 95 71 53 76 80 83 79 86 83 61 85]
[ 9  7 27 80 83 79 11 34]


In [98]:
# 算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [99]:
# 数组跟标量
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3)
print(a*3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [ ]:
# 广播机制:1.获取形状 2.应用规则
a = np.array([1,2,3]) # 1x3
b = np.array([[4],[5],[6]]) # 3x1
print(a+b)
'''
a
1 2 3
1 2 3
1 2 3

b
4 4 4
5 5 5
6 6 6
'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a @ b) # @算矩阵乘法

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 2.3 numpy中的常用函数
## 1. 基本数学函数

In [9]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
a = np.array([1,25,81])
print(np.sqrt(a))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [ ]:
# 计算指数 e^x=y
print(np.exp(1))

2.718281828459045


In [13]:
# 计算自然对数 lny=x
print(np.log(2.71))

0.9969486348916096


In [18]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [20]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [21]:
# 计算a的b次幂
print(np.power(arr, 2))

[1 1 4 9]


In [ ]:
print(np.round([3.2, 4.50, 8.1, 9.6])) # 4.51可以算作5

[ 3.  4.  8. 10.]


In [24]:
# 向上取整，向下取整

In [26]:
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))

[ 2. 26. 82.]


In [27]:
# 检测缺失值NaN
np.isnan([1, 2, 3, np.nan])

array([False, False, False,  True])

In [ ]:
arr = np.array()