## 第2章 Numpy科学计算综合练习

In [ ]:
'''
题目 1:温度数据分析
某城市一周的最高气温(°C)为[28,30,29,31,32,30,29]
-计算平均气温、最高气温和最低气温。
-找出气温超过30°C的天数。
'''

In [2]:
import numpy as np
temps = np.array([28,30,29,31,32,30,29])
print('平均气温：%.3f' % np.mean(temps))
print('最高气温：', np.max(temps))
print('最低气温：', np.min(temps))

for i in range(np.size(temps)):
    if temps[i] > 30:
        print('第',i+1,'天超过30°C')

print('气温超过30°C的天数：',len(temps[temps>30]))

print((np.cumsum(np.where(temps>30,1,0)))[-1])

平均气温：29.857
最高气温： 32
最低气温： 28
第 4 天超过30°C
第 5 天超过30°C
气温超过30°C的天数： 2
2


In [ ]:
'''
题目 2: 学生成绩统计
某班级 5 名学生的数学成绩为 [85,90,78,92,88]。
- 计算成绩的平均分、中位数和标准差。
- 将成绩转换为百分制 (假设满分为10)。
'''

In [4]:
import numpy as np
score = np.array([85,90,78,92,88])
print(score)
print(np.sort(score))
print('平均分：',np.mean(score))
print('中位数：',np.median(score))
print('标准差：%.3f' % np.std(score))

[85 90 78 92 88]
[78 85 88 90 92]
平均分： 86.6
中位数： 88.0
标准差：4.883


In [ ]:
'''
题目 3: 矩阵运算
给定矩阵 A=[[1, 2], [3, 4]] 和 B=[[5, 6], [7, 8]]
- 计算 A+B 和 A*B (逐元素乘法)。
- 计算 A 和 B 的矩阵乘法 (点积)。
'''

In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A,B,sep='\n')
print(A + B)
print(A * B)
print(A @ B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
'''
题目 4: 随机数据生成
生成一个(3,4)的随机整数数组，范围 [0,10)。
- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为 -1。
'''

In [ ]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print('每列最大值：',np.max(arr,axis=0))
print('每行的最小值', np.min(arr, axis=0))

print(np.where(arr%2==1, -1, arr))
# bool索引，起到和where相同的作用——
# arr[arr%2==1] = -1

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列最大值： [7 9 7 6]
每行的最小值 [2 0 3 3]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [ ]:
''' 
题目 5:数组变形
创建一个1到12的一维数组,并转换为(3, 4)的二维数组
- 计算每行的和与每列的平均值
- 将数组展平为一维数组
'''

In [ ]:
arr = np.arange(1, 13)
print(arr)
arr = arr.reshape(3,4)
print(arr)
print('每行的和：', np.sum(arr,axis=1))
print('每列的平均值：', np.mean(arr, axis=0))
print(np.reshape(arr, (12))) # 不一样的方法
arr = arr.reshape(12)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和： [10 26 42]
每列的平均值： [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
''' 
题目 6:布尔索引
生成一个(5,5)的随机数组,范围[0,20)。
- 找出数组中大于10的元素。
- 将所有大于10的元素替换为0。
'''

In [ ]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10,0,arr))
# arr[arr>10] = 0
np.where(arr>10,0,arr) # where不修改array
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]
[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]


In [ ]:
''' 
题目 7:统计函数应用
某公司 6 个月的销售额 (万元) 为 [120,135,110,125,130,140]
- 计算销售额的总和、均值和方差
- 找出销售额最高的月份和最低的月份
'''

In [ ]:
money = np.array([120, 135, 110, 125, 130, 140])
print('总和：', np.sum(money))
print('平均值：', np.mean(money))
print('方差：', np.var(money))
print('最高的月份：', np.argmax(money)+1)
print('最低的月份：', np.argmin(money)+1)

总和： 760
平均值： 126.66666666666667
方差： 97.22222222222223
最高的月份： 6
最低的月份： 3


In [ ]:
''' 
题目8:数组拼接
给定A = [1, 2, 3] 和B = [4, 5, 6]。
- 将A和B水平拼接为一个新数组。
- 将A和B垂直拼接为一个新数组。
'''

' \n题目8:数组拼接\n给定A = [1, 2, 3] 和B = [4, 5, 6]。\n- 将A和B水平拼接为一个新数组。\n- 将A和B垂直拼接为一个新数组。\n'

In [11]:
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate([A,B])
print(C)
print(np.reshape(C,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
''' 
题目 9: 唯一值与排序
给定数组 [2,1,2,3,1,4,3]。
- 找出数组中的唯一值并排序。
- 计算每个唯一值出现的次数。
'''

In [13]:
arr = np.array([2,1,2,3,1,4,3])

In [ ]:
u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr,counts)

for i in range(len(u_arr)):
    print(u_arr[i])
    print(arr[arr==u_arr[i]]) 
    # 遍历arr的每一个元素，和u_arr[i]做相等比较
    # 生成一个和arr形状完全相同的布尔数组
    # True表示对应位置的元素等于u_arr[i]，False表示不等
    # 把布尔数组中True位置对应的arr元素保留下来；
    # 把False位置对应的元素剔除；
    # 最终返回一个一维数组，包含所有筛选出的元素。

[1 2 3 4] [2 2 2 1]
1
[1 1]
2
[2 2]
3
[3 3]
4
[4]
