# 自然语言处理

## 1.神经网络复习

### 1.1 简单神经网络

In [2]:
import numpy as np
W1 = np.random.randn(2, 4) # 权重 2x4
b1 = np.random.randn(4)    # 偏置 1x4
x = np.random.randn(10, 2) # 输入 10x2
# h = np.dot(x, W1) + b1
h = x @ W1 + b1 # 加偏置的时候自动将b1广播成10x4
print(W1,b1,x,h,sep='\n\n')

[[ 1.29330748  0.59751941 -1.07840755  0.55953083]
 [ 1.6611107  -0.5369122  -0.72966564  0.4017214 ]]

[0.07331749 1.82401673 0.23083692 0.28647059]

[[ 1.26705777  0.62492141]
 [ 0.13783474  0.63171667]
 [ 0.36908916  0.21212356]
 [ 2.89725344 -0.16081687]
 [-0.30645992  0.96486947]
 [ 0.11233163  0.25660674]
 [-0.31683715 -0.29542812]
 [ 0.27645137  0.24568541]
 [ 1.15953282  0.12901013]
 [-0.01383933  1.13322508]]

[[ 2.75007642  2.24558042 -1.59155143  1.24647279]
 [ 1.30093152  1.56719927 -0.37874706  0.61736749]
 [ 0.90302398  1.93066294 -0.32197089  0.57820193]
 [ 3.55322242  3.64152644 -2.77624053  1.84296965]
 [ 1.27972558  1.12285078 -0.14270649  0.50260553]
 [ 0.64484903  1.75336176 -0.07753948  0.45240802]
 [-0.82718917  1.79331934  0.78808024 -0.00948936]
 [ 0.83896478  1.85729029 -0.24655853  0.53985074]
 [ 1.78725008  2.44759299 -1.1137463   0.98709109]
 [ 1.93783128  1.20730509 -0.58111404  0.73396782]]


### 1.2 sigmoid函数

In [5]:
def Sigmoid(x):
# 输入是标量、向量、矩阵，输出值介于0-1之间，对每个元素逐元素独立计算
    return 1 / (1 + np.exp(-x))

print(Sigmoid(0))

0.5


### 1.3 变换神经元

In [ ]:
a = sigmoid(h)
print(a) # 10x4
W2 = np.random.randn(4, 3) # 4x3
b2 = np.random.randn(3) # 1x3

s = a @ W2 + b2 # 10x4 @ 4x3 + 1x3
print() 
print(s)

[[0.93991767 0.90426863 0.16916573 0.77668869]
 [0.78599171 0.82738398 0.40642913 0.64961959]
 [0.71157053 0.87332278 0.4201955  0.64065357]
 [0.97216476 0.97445723 0.05862168 0.86329954]
 [0.78240306 0.75451712 0.4643838  0.62307145]
 [0.65584877 0.85237632 0.48062484 0.61121161]
 [0.30423973 0.85733376 0.68741897 0.49762768]
 [0.69824714 0.8649808  0.43867074 0.6317777 ]
 [0.8565898  0.92038525 0.24717312 0.72851298]
 [0.87411369 0.76982177 0.35867629 0.67567538]]

[[ 2.61147637  0.69906898  1.03268438]
 [ 2.02951932  0.25787143  0.97881063]
 [ 1.95669532  0.17325173  0.95373126]
 [ 2.89893745  0.89776125  1.03169628]
 [ 1.92118325  0.20007708  0.9596745 ]
 [ 1.80758311  0.05734825  0.92492565]
 [ 1.2023595  -0.4680883   0.75104221]
 [ 1.91310077  0.14069543  0.94665845]
 [ 2.38774077  0.50951575  1.01594247]
 [ 2.18798257  0.41314145  0.99322458]]


### 1.4 层的类化以及正向传播

In [ ]:
import numpy as np

class sigmoid():
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))

# sigmoid 函数被实现为一个类，主变换处理被实现为forward(x)方法
# 因为Sigmoid层没有需要学习的参数，所以使用空列表初始化实例变量params


# 全连接层Affine层的实现
class Affine():
    def __init__(self, W, b):
        self.params = [W,b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


In [ ]:
class TwoLayerNet():
    def __init__(self, input_size, hidden_size, output_size):
        I,H,O = input_size, hidden_size, output_size

        # 初始化权重和偏置
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 生成层 进行前向传播时数据进行的顺序
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 将所有的权重整理到列表中
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x