# 自然语言处理

## 1.神经网络复习

### 1.1 简单神经网络

In [2]:
import numpy as np
W1 = np.random.randn(2, 4) # 权重 2x4
b1 = np.random.randn(4)    # 偏置 1x4
x = np.random.randn(10, 2) # 输入 10x2
# h = np.dot(x, W1) + b1
h = x @ W1 + b1 # 加偏置的时候自动将b1广播成10x4
print(W1,b1,x,h,sep='\n\n')

[[ 1.29330748  0.59751941 -1.07840755  0.55953083]
 [ 1.6611107  -0.5369122  -0.72966564  0.4017214 ]]

[0.07331749 1.82401673 0.23083692 0.28647059]

[[ 1.26705777  0.62492141]
 [ 0.13783474  0.63171667]
 [ 0.36908916  0.21212356]
 [ 2.89725344 -0.16081687]
 [-0.30645992  0.96486947]
 [ 0.11233163  0.25660674]
 [-0.31683715 -0.29542812]
 [ 0.27645137  0.24568541]
 [ 1.15953282  0.12901013]
 [-0.01383933  1.13322508]]

[[ 2.75007642  2.24558042 -1.59155143  1.24647279]
 [ 1.30093152  1.56719927 -0.37874706  0.61736749]
 [ 0.90302398  1.93066294 -0.32197089  0.57820193]
 [ 3.55322242  3.64152644 -2.77624053  1.84296965]
 [ 1.27972558  1.12285078 -0.14270649  0.50260553]
 [ 0.64484903  1.75336176 -0.07753948  0.45240802]
 [-0.82718917  1.79331934  0.78808024 -0.00948936]
 [ 0.83896478  1.85729029 -0.24655853  0.53985074]
 [ 1.78725008  2.44759299 -1.1137463   0.98709109]
 [ 1.93783128  1.20730509 -0.58111404  0.73396782]]


### 1.2 sigmoid函数

In [5]:
def Sigmoid(x):
# 输入是标量、向量、矩阵，输出值介于0-1之间，对每个元素逐元素独立计算
    return 1 / (1 + np.exp(-x))

print(Sigmoid(0))

0.5


### 1.3 变换神经元

In [ ]:
a = sigmoid(h)
print(a) # 10x4
W2 = np.random.randn(4, 3) # 4x3
b2 = np.random.randn(3) # 1x3

s = a @ W2 + b2 # 10x4 @ 4x3 + 1x3
print() 
print(s)

[[0.93991767 0.90426863 0.16916573 0.77668869]
 [0.78599171 0.82738398 0.40642913 0.64961959]
 [0.71157053 0.87332278 0.4201955  0.64065357]
 [0.97216476 0.97445723 0.05862168 0.86329954]
 [0.78240306 0.75451712 0.4643838  0.62307145]
 [0.65584877 0.85237632 0.48062484 0.61121161]
 [0.30423973 0.85733376 0.68741897 0.49762768]
 [0.69824714 0.8649808  0.43867074 0.6317777 ]
 [0.8565898  0.92038525 0.24717312 0.72851298]
 [0.87411369 0.76982177 0.35867629 0.67567538]]

[[ 2.61147637  0.69906898  1.03268438]
 [ 2.02951932  0.25787143  0.97881063]
 [ 1.95669532  0.17325173  0.95373126]
 [ 2.89893745  0.89776125  1.03169628]
 [ 1.92118325  0.20007708  0.9596745 ]
 [ 1.80758311  0.05734825  0.92492565]
 [ 1.2023595  -0.4680883   0.75104221]
 [ 1.91310077  0.14069543  0.94665845]
 [ 2.38774077  0.50951575  1.01594247]
 [ 2.18798257  0.41314145  0.99322458]]


### 1.4 层的类化以及正向传播

In [6]:
import numpy as np

class Sigmoid():
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))

# sigmoid 函数被实现为一个类，主变换处理被实现为forward(x)方法
# 因为Sigmoid层没有需要学习的参数，所以使用空列表初始化实例变量params


# 全连接层Affine层的实现
class Affine():
    def __init__(self, W, b):
        self.params = [W,b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


In [7]:
class TwoLayerNet():
    def __init__(self, input_size, hidden_size, output_size):
        I,H,O = input_size, hidden_size, output_size

        # 初始化权重和偏置
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 生成层 进行前向传播时数据进行的顺序
        self.layers = [
            Affine(W1, b1), # 创建匿名实例
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 将所有的权重整理到列表中
        self.params = []
        for layer in self.layers:
            self.params += layer.params # 接收所有self.layers层匿名实例的参数

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x) # 让x经过Affine的forward或者Sigmoid的forward获得新的x
        return x

In [10]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x) # 学习的参数被汇总到 model.params 中，进行神经网络学习会更轻松
print(x)
print(s)

[[ 1.2685312   0.41519579]
 [-0.37913303 -0.86452866]
 [-0.14632249 -0.18478503]
 [-0.15099029 -0.83226647]
 [-1.38703718  2.14798274]
 [ 0.71752247  0.25785624]
 [ 1.33208076 -1.24634198]
 [-1.56069314  0.05584941]
 [-0.07278459 -0.90608725]
 [ 2.27463651  0.56476357]]
[[-0.95884724 -1.51624295 -0.85523122]
 [-0.79648919 -0.98806925 -0.59828992]
 [-0.80925591 -1.18455898 -0.76580285]
 [-0.83058787 -1.04743634 -0.61170139]
 [-0.52967083 -1.42908589 -1.33934697]
 [-0.90825879 -1.42721031 -0.85561832]
 [-1.00985549 -1.26717518 -0.55768947]
 [-0.56315395 -0.94445366 -0.8316385 ]
 [-0.84438211 -1.0523871  -0.59897382]
 [-1.03028109 -1.60064208 -0.78790182]]


### 1.5 损失函数
进行计算神经网络的损失要用损失函数，进行多类别分类的神经网络通常使用交叉熵误差作为损失函数

Softmax函数  
$$
y_k = \frac{\exp(s_k)}{\sum_{i=1}^{K} \exp(s_i)}
$$
交叉熵误差  
$$
L = -\sum_{k=1}^{K} t_k \log(y_k)
$$
考虑mini-batch处理的情况下  
$$
L = -\frac{1}{N} \sum_{n=1}^{N} \sum_{k=1}^{K} t_{nk} \log(y_{nk})
$$

**交叉熵的本质，是衡量模型预测概率分布与真实标签的概率分布之间的差异程度**   
例如：  
**单个样本的交叉熵误差**
$$L=−log(y_t)$$

- 模型预测狗的概率 = 0.1——$L=−ln(0.1)≈2.303$（误差大，预测差）
- 模型预测狗的概率 = 1.0——$L=−ln(1.0)=0$（完全预测正确，误差为 0）

**交叉熵误差**    
$$
L = -\sum_{k=1}^{K} t_k \log(y_k)
$$
- K代表类别总数
- $t_k$第$k$类的真实标签（One-Hot编码）,只有真实类别对应的$t_k=1$，其余所有$t_k=0$
- $y_k$模型预测第$k$类的概率（Softmax 输出），所有$y_k \in [0,1]$且$\sum_{k=1}^{K} y_k = 1$
- one-Hot标签$t_k$会“筛选”出真实类别对应的项，令其余项都为0，最终结果和$L=−log(y_t)$完全等价

**考虑mini-batch处理的交叉熵误差**
$$
L = -\frac{1}{N} \sum_{n=1}^{N} \sum_{k=1}^{K} t_{nk} \log(y_{nk})
$$
- $t_{nk}$第$n$个样本的$One-Hot$标签第$k$位
- $y_{nk}$第$n$个样本预测第$k$类的概率（$Softmax$输出）
- 其中先求内层$-\sum_{k=1}^{K} t_{nk} \log(y_{nk})$，再计算外层总和求平均$L = -\frac{1}{N} \sum_{n=1}^{N}(...)$

### 1.6 导数和梯度
$$\frac{\partial L}{\partial x} = (\frac{\partial L}{\partial x_1}, \frac{\partial L}{\partial x_2},...,\frac{\partial L}{\partial x_n})$$

$$
\frac{\partial L}{\partial W} = \begin{pmatrix}
\frac{\partial L}{\partial W_{11}} & \dots & \frac{\partial L}{\partial W_{1n}} \\
\vdots & \ddots & \vdots \\
\frac{\partial L}{\partial W_{n1}} & \dots & \frac{\partial L}{\partial W_{nn}}
\end{pmatrix}
$$

In [ ]:
# 分支节点的Repeat节点
import numpy as np
D, N = 8, 7
x = np.random.randn(1, D)   # 输入
print(x)
y = np.repeat(x, N, axis=0) # 正向传播，将x复制N份，延行复制
print()
dy = np.random.randn(N, D)  # 假设的梯度
print(dy)
print()

dx = np.sum(dy, axis=0, keepdims=True) # 反向传播，对dy按行求和，保持1x8的维度而不是(8,)，避免后续维度错误
print(dx)

[[-0.69079021 -1.11518018 -1.20656774  0.52318957 -0.70841891  0.60883023
  -1.44466263 -1.34057558]]

[[-1.08044853  0.19929337  0.05955129 -2.00424302 -1.25197977  0.6146696
  -0.95508466 -0.62727732]
 [-0.28623312  1.83423346 -0.9556848  -1.200746    0.377456    0.41328843
   0.51225217 -0.42947213]
 [ 0.66187925 -1.11991869 -0.39060277  0.75680531 -0.89239372  1.22546788
   0.75659825 -0.78219873]
 [ 0.73938643 -0.23571643 -0.19190544 -0.22256594 -0.49596528 -2.07347612
  -1.11161378  0.18766625]
 [ 0.90897988 -0.14002144  1.67202963  0.08599149  1.2293971  -0.0379657
   0.65699602 -1.11224339]
 [-0.5539701   1.80670732  1.32610868 -1.00918578  0.87361882 -1.44897479
   2.29766967 -0.34446705]
 [ 1.24143188 -0.67703707 -1.47005709  0.99974155  0.46627147  1.06082319
   1.53526677 -0.93135038]]

[[ 1.63102569  1.66754053  0.0494395  -2.59420239  0.30640463 -0.24616751
   3.69208444 -4.03934275]]


In [ ]:
# Sum节点
import numpy as np
D, N = 8, 7
x = np.random.randn(N, D) # 输入
y = np.sum(x, axis=0, keepdims=True) # 正向传播

dy = np.random.randn(1, D) # 假设的梯度
dx = np.random.randn(dy, N, axis=0) # 反向传播
# 正向传播通过np.sum()实现，反向传播通过np.repeat()实现

In [ ]:
# Matrix Multiply
class Matmul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out
    
    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

### 1.7 梯度的推导和反向传播的实现

$$y=sigmod(x)=\frac{1}{1+e^{-x}}$$
$$\frac{\partial L}{\partial x}=y(1-y)$$
$$x→sigmoid→y$$
$$\frac{\partial L}{\partial y}y(1-y)←sigmoid←\frac{\partial L}{\partial y}$$

In [1]:
# Python 实现sigmoid层
class Sigmoid:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None

    def forward(self, x):
        out = 1 / (1+ np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

In [ ]:
# Affine层
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        self.x = x
        return out
    
    def backward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        self.x = x
        return out
    
    def backward(self, dout):
        W, b = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.X.T, dout)
        db = np.sum(dout, axis=0)
        
        self.grads[0][:] = dW
        self.grads[1][:] = db
        return dx