# defaultdict

defaultdict是Python 自带的增强版字典，提前设定一个默认值

In [ ]:
import numpy as np
X = np.zeros((3,3))
print(X)
v = {}
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        state = (i, j)
        v[state] = 0
print(v)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
{(0, 0): 0, (0, 1): 0, (0, 2): 0, (1, 0): 0, (1, 1): 0, (1, 2): 0, (2, 0): 0, (2, 1): 0, (2, 2): 0}


In [5]:
# defaultdict
import numpy as np
from collections import defaultdict
V = defaultdict(lambda: 0)
print(V)
print(V[100,100])

defaultdict(<function <lambda> at 0x000001E1A5D42200>, {})
0
