# 1.Numpy基础

## 1.1 生成Numpy数组

### 1.1.1从已有数据中创建数组

#### 1)将列表转换成ndarray

In [1]:
import numpy as np
lst1 = [3.14, 2.17, 0, 1, 2]
nd1 = np.array(lst1)
print(nd1)

[3.14 2.17 0.   1.   2.  ]


#### 2)嵌套列表转为多维数组

In [2]:
lst2 = [[3.14, 1, 2, 0],[9, 8, 7, 6]]
print(lst2)
nd2 = np.array(lst2)
print(nd2)

[[3.14, 1, 2, 0], [9, 8, 7, 6]]
[[3.14 1.   2.   0.  ]
 [9.   8.   7.   6.  ]]


### 1.1.2 利用random模块生成数组

|函数|描述|
|:---:|:---:|
|np.random.random|生成0到1之间的随机数|
|np.random.uniform|生成均匀分布的随机数|
|np.random.randn|生成标准正态的随机数|
|np.random.randint|生成随机的整数|
|np.random.normal|生成正态分布|
|np.random.shuffle|随机打乱顺序|
|np.random.seed|设置随机数种子|
|random_sample|生成随机的浮点数|

#### 1)np.random.random

In [6]:
np3 = np.random.random([3,3])
print(np3)
print()
print(np3.shape)

[[0.80020917 0.197792   0.57227444]
 [0.48661032 0.85178922 0.65113624]
 [0.00357426 0.29096685 0.53062563]]

(3, 3)


#### 2)np.random.randn

In [ ]:
np.random.seed(123)
np4 = np.random.randn(2, 3)
print(np4)
np.random.shuffle(np4)
print('随机打乱后的数据', np4, sep='\n')
# 这里(3,3)形状的np4打乱前后相同想想为什么

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
随机打乱后的数据
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]


#### 1.3创建特定形状的多维数组
|函数|描述|
|:---:|:---:|
|np.zeros((3,4))|创建3×4的元素全为0的数组|
|np.ones((3,4))|创建3×4的元素全为1的数组|
|np.empty(2,3)|创建2×3的空数组，空数组中的值并不为0，而是未初始化的垃圾值|
|np.zeros_like(ndarr)|以ndarr相同维度创建元素全为0数组|
|np.ones_like(ndarr)|以ndarr相同维度创建元素全为1数组|
|np.empty_like(ndarr)|以ndarr相同维度创建空数组|
|np.eye(5)|该函数用于创建一个5×5单位矩阵|
|np.full((3,5), 666)|创建3×5的元素全为666的数组，666为指定值|


In [20]:
#### 例子

np5 = np.zeros((3,3))
print()
np6 = np.zeros_like(np5)
print()
np7 = np.eye(3)
print()
np8 = np.diag([1,2,3])
print(np5)
print(np6)
print(np7)
print(np8)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### 1.1.4 利用arange、linspace函数生成数组

#### 1)arange

In [22]:
print(np.arange(10))
print(np.arange(0,10))
print(np.arange(1,4,0.5))
print(np.arange(9,-1,-1))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5]
[9 8 7 6 5 4 3 2 1 0]


#### 2)linspace
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)


In [ ]:
print(np.linspace(0, 1, 10)) # 因其包含起点终点，步长为(1-0)/9=0.11111111

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## 1.2 获取元素

In [ ]:
# 创建数据
np.random.seed(2019)
np11 = np.random.random([101])

# 获取数据
print(np11[3])    # 截取一个
print(np11[3:6])  # 截取一段
print(np11[1:6:2])# 间隔取数
print(np11[::-2]) # 倒叙

np12 = np.arange(25).reshape([5,5])
print(np12)
print(np12[1:3,1:3]) # 截取区域内数据
print(np12[(np12>3) & (np12<10)]) # 截取一个多维数组中数值在一个值域之中的数据

print(np12[[1,2]]) # 读取指定两行，或者print(np12[1:3,:])
print(np12[:,1:3]) # 读取2，3列

0.6378774010222266
[0.6378774  0.88049907 0.29917202]
[0.39308051 0.6378774  0.29917202]
[0.09043587 0.33301237 0.74712639 0.4912929  0.71621612 0.01268605
 0.41795559 0.18086473 0.58357617 0.22681295 0.22553455 0.38845353
 0.95600191 0.90343476 0.42188698 0.32958304 0.43428899 0.85179036
 0.29711244 0.35362047 0.45246511 0.38464466 0.0380261  0.32879374
 0.38285364 0.23452664 0.58102448 0.68218738 0.32329947 0.57381853
 0.30448392 0.17100016 0.84518556 0.92799464 0.70339235 0.90448733
 0.50907615 0.27812941 0.52664983 0.29928265 0.51361992 0.20112905
 0.03236122 0.14847623 0.16286487 0.45244662 0.88138193 0.70219827
 0.88049907 0.62396996 0.90348221]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 6  7]
 [11 12]]
[4 5 6 7 8 9]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


## 1.3 Numpy算术运算

### 1.3.1 对应元素相乘

In [ ]:
A = np.array([[1,2], [-1, 4]])
B = np.array([[2, 0], [3, 4]])
print(A, B, A*B, sep= '\n\n')
print()
print(np.multiply(A,B))
print()
print(A*2.0)



[[ 1  2]
 [-1  4]]

[[2 0]
 [3 4]]

[[ 2  0]
 [-3 16]]

[[ 2  0]
 [-3 16]]

[[ 2.  4.]
 [-2.  8.]]


### 1.3.2 点积运算
**np.dot(X1, X2)**

In [40]:
X1 = np.array([[1,2], [2,3]])
X2 = np.array([[1,2,3], [4,5,6]])
X3 = np.dot(X1, X2)
print(X3)

[[ 9 12 15]
 [14 19 24]]


## 1.4 数组变形

#### 1.4.1 更改数组形状
|函数|描述|
|:---:|:---:|
|arr.reshape|重新将向量arr进行维度变换，不修改向量本身|
|arr.resize|重新将向量arr进行维度变化，修改向量本身|
|arr.T|对向量arr进行转置|
|arr.flatten|对向量arr进行展平，即将多维数组变为1为数组，不会产生原数组的副本|
|arr.squeeze|只能对维数为1的维度降维。对多维数组使用时不会报错，但是不会产生任何影响|
|arr.transpose|对高维矩阵进行轴对换|

**1）reshape**不修改向量本身  
可以只指定行或列进行变换，其余用-1代替

In [ ]:
arr = np.arange(10)
print(arr)
print(arr.reshape(5,2))
print(arr.reshape(5,-1))
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


**2）resize**修改向量本身

In [45]:
arr = np.arange(10)
print(arr)
arr.resize(5,2)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3）T**转置

In [47]:
arr = np.arange(10).reshape(5,2)
print(arr)
print(arr.T)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


**4)ravel**向量展平
分为行展开列展开

In [55]:
arr = np.arange(6).reshape(2, -1)
print(arr)
print('按照列展开优先', arr.ravel('F'), sep='\n')
print('按照行展开优先', arr.ravel(), sep='\n')

[[0 1 2]
 [3 4 5]]
按照列展开优先
[0 3 1 4 2 5]
按照行展开优先
[0 1 2 3 4 5]


**5）flatten**矩阵转换为向量

In [59]:
arr = np.floor(10*np.random.random((3, 4)))
print(arr)
print(arr.flatten())

[[3. 0. 9. 0.]
 [1. 2. 4. 2.]
 [9. 1. 5. 1.]]
[3. 0. 9. 0. 1. 2. 4. 2. 9. 1. 5. 1.]


**6）squeeze**降维，将矩阵中含1的维度去掉

In [65]:
arr = np.arange(3).reshape(3, 1)
print(arr.shape)
print(arr)
print(arr.squeeze().shape)
print(arr.squeeze())

(3, 1)
[[0]
 [1]
 [2]]
(3,)
[0 1 2]


**7）transpose**对高维矩阵进行轴对换  
transpose(1,2,0) → 将矩阵(0, 1, 2)维度变换为(1, 2, 0)

In [70]:
arr = np.arange(24).reshape(2,3,4)
print(arr.shape)
print(arr.transpose(1,2,0).shape)

(2, 3, 4)
(3, 4, 2)


#### 1.4.2 合并数组
|函数|描述|
|:---:|:---:|
|np.append|内存占用大|
|np.concatenate|没有内存问题|
|np.stack|沿着新的轴加入一系列数组|
|np.hstack|堆栈数组垂直顺序（行）|
|np.vstack|堆栈数组垂直顺序（列）|
|np.dstack|堆栈数组按顺序深入|
|np.vsplit|将数组分解成垂直的多个子数组的列表|

**1）append**

In [74]:
# 合并一维数组
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a, b)
print(c)
# 合并多维数组
a = np.arange(4).reshape(2, 2)
b = np.arange(4).reshape(2, 2)
# 按行合并
c = np.append(a, b, axis=0)
print(c)
# 按列合并
d = np.append(a, b, axis=1)
print(d)

[1 2 3 4 5 6]
[[0 1]
 [2 3]
 [0 1]
 [2 3]]
[[0 1 0 1]
 [2 3 2 3]]


**2）concatenate**沿指定轴连接数组或者矩阵

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
# 按行合并
c = np.concatenate((a, b), axis=0)
print(c)
# 按列合并
d = np.concatenate((a, b.T), axis=1)
print(d)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


**3）stack**沿指定轴堆叠数组或矩阵

In [79]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.stack((a, b), axis=0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 1.5 批量处理
大数据拆成多个批次：  
- 1）得到数据集
- 2）随机打乱数据
- 3）定义批次大小
- 4）批处理数据集

In [82]:
# 生成10000个形状2×3的矩阵
data_train = np.random.randn(10000, 2, 3)
print(data_train.shape)

# 打乱
np.random.shuffle(data_train)

# 定义批次大小
batch_size = 100

# 进行批处理
for i in range(0, len(data_train), batch_size):
    x_batch_sum = np.sum(data_train[i:i+batch_size])
    print(f'第{i}批次，该批次的数据之和：{x_batch_sum}')

(10000, 2, 3)
第0批次，该批次的数据之和：7.620812048795978
第100批次，该批次的数据之和：-4.397148203089865
第200批次，该批次的数据之和：22.212238067455164
第300批次，该批次的数据之和：14.625050160804637
第400批次，该批次的数据之和：-29.803403863206867
第500批次，该批次的数据之和：-4.25568124653153
第600批次，该批次的数据之和：-6.074194271803006
第700批次，该批次的数据之和：22.174041094957822
第800批次，该批次的数据之和：6.977053465400206
第900批次，该批次的数据之和：5.196262675919904
第1000批次，该批次的数据之和：38.26631064834709
第1100批次，该批次的数据之和：1.373490145470329
第1200批次，该批次的数据之和：-21.982795494524645
第1300批次，该批次的数据之和：30.48768062359178
第1400批次，该批次的数据之和：-16.788368948382836
第1500批次，该批次的数据之和：39.726660159927384
第1600批次，该批次的数据之和：-18.26079164872136
第1700批次，该批次的数据之和：49.747781066819385
第1800批次，该批次的数据之和：20.815649192056558
第1900批次，该批次的数据之和：-20.37846384343898
第2000批次，该批次的数据之和：29.564660185932418
第2100批次，该批次的数据之和：23.401290836262554
第2200批次，该批次的数据之和：2.531193097617649
第2300批次，该批次的数据之和：17.03489843407585
第2400批次，该批次的数据之和：3.735496475173943
第2500批次，该批次的数据之和：7.4009081665941
第2600批次，该批次的数据之和：57.40524610155442
第2700批次，该批次的数据之和：-25.799755741715686
